version: '2'

#services:
services:
  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"

  student-service:
    build:
      context: spring-cloud-consul-student-service
      dockerfile: Dockerfile
    depends_on:
      - consul
    links:
      #- consul:latest
      - consul:consul
    ports:
      - "9098:9098"

  school-service:
    build:
      context: spring-cloud-consul-school-service
      dockerfile: Dockerfile
    depends_on:
      - consul
    links:
     #- consul:latest
      - consul:consul
    ports:
      - "8098:8098"